import torch.nn as nn
import numpy as np

NB_SAMPLES = 1000
DATA_DIR = './data'

NUMBER_OF_CLASSES = 10

WIDTH_HEIGHT = 14
SINGLE_IMAGE_SIZE = WIDTH_HEIGHT * WIDTH_HEIGHT
DOUBLE_IMAGE_SIZE = 2 * SINGLE_IMAGE_SIZE

# ----Train Config-----#
LEARNING_RATE = 0.001
TRAIN_BATCH_SIZE = 5
SUB_CRITERION = nn.CrossEntropyLoss()
FINAL_CRITERION = nn.BCELoss()
EPOCHS = 20

# ----AuxLoss Config-----#
ALPHA = 0.5
BEST_ALPHA = 0.22

# ----Search Config-----#
KERNEL_SIZES = [3,5]
NB_CHANNELS = [4,8,16,24,48]
FCNEURONS = [32,64,128, 256,512]
NB_LAYERS = [1, 2, 3]
ALPHAS = np.linspace(0, 1, 10)

#----Test Config-----#
TEST_BATCH_SIZE = NB_SAMPLES

#----BasicNet Config-----#
BASIC_NET_NAME = "basic_net"
BASIC_NET_HIDDEN_LAYER = 128
BASIC_NET_NB_HIDDEN = 1

#----OscarNet Config-----#
OSCAR_NET_NAME = "oscar_net"
OSCAR_NET_HIDDEN_LAYER = 128
OSCAR_NET_NB_HIDDEN = 1

#----RobertNet Config-----#
ROBERT_NET_NAME = "robert_net"
ROBERT_NET_HIDDEN_LAYER = 128
ROBERT_NET_BASE_CHANNEL_SIZE = 8
ROBERT_NET_NB_HIDDEN = 1

#----MaryJaneNet Config-----#
MARYJANE_NET_NAME = "maryjane_net"
MARYJANE_NET_HIDDEN_LAYER = 128
MARYJANE_NET_BASE_CHANNEL_SIZE = 8
MARYJANE_NET_NB_HIDDEN = 1
MARYJANE_NET_KERNEL_SIZE = 3

MARYJANE_BEST_HIDDEN = 64
MARYJANE_BEST_CHANNEL = 48
MARYJANE_BEST_KERNEL_SIZE = 3

#----DesmondNet Config-----#
DESMOND_NET_NAME = "desmond_net"
DESMOND_NET_HIDDEN_LAYER = 256
DESMOND_NET_NB_HIDDEN = 2

#----LeonardtNet Config-----#
LEONARD_NET_NAME = "leonard_net"
LEONARD_NET_HIDDEN_LAYER = 256
LEONARD_NET_NB_HIDDEN = 2

LEONARD_BEST_HIDDEN = 256